---
- hosts: webservers
  vars:
      dotfiles_dir: "{{ lookup('env','HOME') }}/dotfiles"
  tasks:
    - name: Installing packages
      package: pkg={{ item }} state=installed update_cache=True
      with_items:
        - curl
        - git
        - vim
        - zsh
        - tmux
        - stow
        - ranger

    - name: Cloning dotfiles
      git:
        repo: https://github.com/diwasblack/dotfiles
        dest: "{{ dotfiles_dir }}"
      become: yes
      become_user: "{{ lookup('env', 'USER') }}"

    - name: Linking dotfiles
      shell: cd "{{ dotfiles_dir }}" && stow --no-folding {{item}}
      become: yes
      become_user: "{{ lookup('env', 'USER') }}"
      with_items:
          - vim
          - zsh
          - bash
          - ranger

    - name: Installing antibody for zsh
      shell: curl -sL git.io/antibody | bash -s
      become: yes
      become_user: "{{ lookup('env', 'USER') }}"
