#!/bin/bash

function attach-or-create-tmux-session() {
    local project_path=$1

    # Obtain the session name to use
    local name=$(basename $project_path)

    # Check if session exists-stores status in exit code
    tmux has-session -t $name
    local tmux_status=$?

    # Attach and return if the session is present
    if [ "${tmux_status}" = "0" ]; then
        echo "Session found"
        tmux attach-session -t $name
        return
    fi

    # Create new session
    tmux new-session -d -c $project_path -s $name
    tmux send-keys "nvim -S ~/.vim_sessions/${name}" C-m
    tmux rename-window -t $name:1 'nvim'

    # Open zsh windows
    tmux new-window -a -c $project_path -t $name:1 -n "zsh1"
    tmux new-window -a -c $project_path -t $name:2 -n "zsh2"

    # Open ranger
    tmux new-window -a -c $project_path -t $name:3 -n "ranger"
    tmux send-keys "ranger" C-m

    # Focus on editor window
    tmux select-window -t $name:1

    # Attach the tmux session created
    tmux attach-session -t $name
}


alias tmuxf="attach-or-create-tmux-session"
